/**
 * history/types.ts — shared TypeScript types for the doc history system.
 *
 * These mirror the Go structs in apps/cli/internal/history/gitlog.go and
 * the JSON returned by GET /api/projects/{project}/docs/{docPath}/history.
 */

/** Who authored this commit. */
export type AuthorKind =
  | 'human'
  | 'claude-code'
  | 'copilot'
  | 'codex'
  | 'gemini'
  | 'vedox-agent';

/** Semantic kind of a prose block. */
export type BlockKind =
  | 'frontmatter'
  | 'heading'
  | 'paragraph'
  | 'code_fence'
  | 'list_item';

/** The type of change applied to a block. */
export type ChangeType = 'added' | 'removed' | 'modified' | 'moved';

/** A single block-level change in a commit. */
export interface BlockChange {
  /** Change direction. */
  type: ChangeType;
  /** Kind of block this change affected. */
  blockKind: BlockKind;
  /**
   * Heading that contextualises this block (the nearest preceding heading
   * in the document, or empty string for frontmatter / top-of-file blocks).
   */
  section: string;
  /** Content before the change (empty for 'added'). */
  before: string;
  /** Content after the change (empty for 'removed'). */
  after: string;
}

/** A single history entry — one Git commit. */
export interface HistoryEntry {
  commitHash: string;
  author: string;
  authorEmail: string;
  authorKind: AuthorKind;
  /** RFC 3339 UTC timestamp. */
  date: string;
  /** Raw Git commit message (first line). */
  message: string;
  /** Human-readable prose summary generated by the backend. */
  summary: string;
  /** Block-level diffs for this commit. */
  changes: BlockChange[];
}

/** Filter state for the timeline. */
export interface HistoryFilter {
  authorKind: 'all' | AuthorKind;
  /** ISO date string (YYYY-MM-DD) or empty string = no lower bound. */
  since: string;
  /** ISO date string (YYYY-MM-DD) or empty string = no upper bound. */
  until: string;
}
